version: 2
updates:
  - package-ecosystem: sbt
    directory: /
    schedule:
      interval: weekly
    ignore:
      - dependency-name: org.scala-sbt:sbt
        versions: [">= 2.a", "< 3"]

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
